persistence:
  accessModes:
    - ReadWriteOnce
  size: 20Gi

resources:
  gvmd:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 4Gi
  ospdOpenvas:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 4Gi
  openvasd:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
  postgres:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
  redis:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
