apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvas-api.fullname" . }}
  labels:
    {{- include "openvas-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "openvas-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
