apiVersion: apps/v1
kind: Deployment
metadata:
    name: notus-data
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: notus-data
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: notus-data
    template:
        metadata:
            name: ""
            labels:
                app.kubernetes.io/name: notus-data
        spec:
            containers:
                - name: notus-data
                  image: registry.community.greenbone.net/community/notus-data
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: KEEP_ALIVE
                      value: "1"
                  volumeMounts:
                    - name: volume-notus-data-vol
                      mountPath: /mnt
            volumes:
                - name: volume-notus-data-vol
                  persistentVolumeClaim:
                    claimName: notus-data-vol
