apiVersion: apps/v1
kind: Deployment
metadata:
    name: cert-bund-data
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: cert-bund-data
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: cert-bund-data
    template:
        metadata:
            name: ""
            labels:
                app.kubernetes.io/name: cert-bund-data
        spec:
            containers:
                - name: cert-bund-data
                  image: registry.community.greenbone.net/community/cert-bund-data
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: KEEP_ALIVE
                      value: "1"
                  volumeMounts:
                    - name: volume-cert-data-vol
                      mountPath: /mnt
            volumes:
                - name: volume-cert-data-vol
                  persistentVolumeClaim:
                    claimName: cert-data-vol
