apiVersion: apps/v1
kind: Deployment
metadata:
    name: pg-gvm-migrator
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: pg-gvm-migrator
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: pg-gvm-migrator
    template:
        metadata:
            name: ""
            labels:
                app.kubernetes.io/name: pg-gvm-migrator
        spec:
            containers:
                - name: pg-gvm-migrator
                  image: registry.community.greenbone.net/community/pg-gvm-migrator:stable
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                    - name: volume-psql-data-vol
                      mountPath: /var/lib/postgresql
                    - name: volume-psql-socket-vol
                      mountPath: /var/run/postgresql
            volumes:
                - name: volume-psql-data-vol
                  persistentVolumeClaim:
                    claimName: psql-data-vol
                - name: volume-psql-socket-vol
                  persistentVolumeClaim:
                    claimName: psql-socket-vol
