apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-objects-vol
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: data-objects-vol
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
