apiVersion: v1
kind: Service
metadata:
    name: report-formats
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: report-formats
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    clusterIP: None
    selector:
        app.kubernetes.io/name: report-formats
