apiVersion: v1
kind: Service
metadata:
    name: data-objects
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: data-objects
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    clusterIP: None
    selector:
        app.kubernetes.io/name: data-objects
