apiVersion: v1
kind: Service
metadata:
    name: pg-gvm
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: pg-gvm
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    clusterIP: None
    selector:
        app.kubernetes.io/name: pg-gvm
