apiVersion: v1
kind: Service
metadata:
    name: redis-server
    namespace: greenbone-community-edition
    labels:
        app.kubernetes.io/name: redis-server
        app.kubernetes.io/part-of: greenbone-community-edition
spec:
    selector:
        app.kubernetes.io/name: redis-server
    ports:
        - name: http
          port: 6379
          targetPort: 6379
          protocol: TCP
