from fastapi import APIRouter, HTTPException, Path
from pydantic import BaseModel, Field

from gmp import GVM_ERRORS, find_by_name, gmp_session

router = APIRouter(tags=["scans"])


class CreateScanRequest(BaseModel):
    name: str = Field(description="Display name for the scan task")
    target_id: str = Field(description="GVM target UUID to scan (from `POST /targets`)")
    config_id: str | None = Field(
        default=None,
        description="Scan config UUID (from `GET /scan-configs`). Omit to use *Full and fast*.",
    )
    scanner_id: str | None = Field(
        default=None,
        description="Scanner UUID (from `GET /scanners`). Omit to use *OpenVAS Default*.",
    )


class ScanCreated(BaseModel):
    task_id: str = Field(description="GVM task UUID")
    report_id: str = Field(description="UUID of the report being generated by this run")


class Scan(BaseModel):
    id: str = Field(description="GVM task UUID")
    name: str = Field(description="Display name of the task")
    status: str = Field(description="Current task status, e.g. `Running`, `Done`, `New`")
    progress: int = Field(description="Completion percentage (0–100), or -1 if not started")


@router.get(
    "/scans",
    response_model=list[Scan],
    summary="List scan tasks",
    response_description="All scan tasks configured in GVM",
    responses=GVM_ERRORS,
)
def list_scans() -> list[Scan]:
    """Return all scan tasks defined in GVM along with their current status.

    Poll this endpoint (or `GET /scans/{task_id}`) to track progress after
    starting a scan via `POST /scans`.
    """
    with gmp_session() as gmp:
        response = gmp.get_tasks()

    return [
        Scan(
            id=t.get("id", ""),
            name=t.findtext("name", ""),
            status=t.findtext("status", ""),
            progress=int(t.findtext("progress", "-1") or -1),
        )
        for t in response.findall("task")
    ]


@router.get(
    "/scans/{task_id}",
    response_model=Scan,
    summary="Get a scan task",
    response_description="Current state of the requested task",
    responses={
        404: {"description": "Task not found"},
        **GVM_ERRORS,
    },
)
def get_scan(task_id: str = Path(description="GVM task UUID")) -> Scan:
    """Return the current status and progress of a single scan task."""
    with gmp_session() as gmp:
        response = gmp.get_task(task_id=task_id)

    task = response.find("task")
    if task is None:
        raise HTTPException(404, detail=f"Task {task_id} not found")

    return Scan(
        id=task.get("id", ""),
        name=task.findtext("name", ""),
        status=task.findtext("status", ""),
        progress=int(task.findtext("progress", "-1") or -1),
    )


@router.post(
    "/scans",
    response_model=ScanCreated,
    status_code=202,
    summary="Create and start a scan",
    response_description="UUIDs of the created task and its initial report",
    responses=GVM_ERRORS,
)
def create_scan(body: CreateScanRequest) -> ScanCreated:
    """Create a GVM task and immediately start it.

    The task and its first report are created atomically in a single GMP
    session. Use the returned `task_id` to poll `GET /scans/{task_id}` for
    progress, and `report_id` to fetch results via `GET /reports/{report_id}`
    once the scan completes.
    """
    with gmp_session() as gmp:
        config_id = body.config_id
        if not config_id:
            configs = gmp.get_scan_configs().findall("config")
            if not configs:
                raise HTTPException(502, detail="No scan configs available in GVM")
            config_id = find_by_name(configs, "Full and fast") or configs[0].get("id")

        scanner_id = body.scanner_id
        if not scanner_id:
            scanners = gmp.get_scanners().findall("scanner")
            if not scanners:
                raise HTTPException(502, detail="No scanners available in GVM")
            scanner_id = find_by_name(scanners, "OpenVAS Default") or scanners[0].get("id")

        task_resp = gmp.create_task(
            name=body.name,
            config_id=config_id,
            target_id=body.target_id,
            scanner_id=scanner_id,
        )
        task_id = task_resp.get("id")
        if not task_id:
            raise HTTPException(502, detail="GVM did not return a task ID")

        start_resp = gmp.start_task(task_id=task_id)

    report_id = start_resp.findtext("report_id", "")
    return ScanCreated(task_id=task_id, report_id=report_id)
