apiVersion: v1
kind: Service
metadata:
  name: {{ include "greenbone.fullname" . }}
  labels:
    {{- include "greenbone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "greenbone.selectorLabels" . | nindent 4 }}
  ports:
    - name: gsa
      port: {{ .Values.service.ports.gsa }}
      targetPort: gsa
      protocol: TCP
